on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  schedule:
    - cron: "0 3 * * *"

name: Create Release LIVE

jobs:
  build:
    name: Create Release LIVE
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get New Commits
        run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_ENV

      - name: Get Date
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        id: date
        run: echo "date=$(date '+%d.%m.%y')" >> $GITHUB_OUTPUT

      - name: Create Zip
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        run: |
          sudo timedatectl set-timezone Europe/Berlin
          mkdir release
          cp "live/user.cfg" "release"
          mkdir -p "release/data/Localization/german_(germany)"
          cp "live/global.ini" "release/data/Localization/german_(germany)/"
          cd release
          echo "${{ vars.VERSION_FILE_TEXT }} ${{ steps.date.outputs.date }} - %H:%M Uhr')" >> Versionstext.txt
          mv Versionstext.txt Version-${{ steps.date.outputs.date }}.txt
          zip -r "../${{ vars.ZIP_NAME_LIVE }}" *

      - name: Create Release
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.date.outputs.date }}
          commit: main
          name: ${{ vars.RELEASE_TITLE_LIVE }}
          body: ${{ vars.RELEASE_BODY_LIVE }}
          artifacts: ${{ vars.ZIP_NAME_LIVE }}