name: global.ini Tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  No_Missing_Keys:
    name: Check For Missing Keys
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Execute Test
        run: python ./.github/tests/key_test.py

  Matching_Encoding:
    name: Ensure Matching Encodings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install chardet

      - name: Execute Test
        run: python ./.github/tests/encoding_test.py

  check_whiteSpace_comma:
    name: Check no whitespace before a comma
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install chardet

      - name: Execute Test
        run: python ./.github/tests/check_for_whitespace_before_comma.py