name: Tests

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

jobs:
  No_Missing_Keys:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Execute test
        run: python ./github/tests/key_test.py

  Matching_Encoding:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v2
      
            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install chardet
            - name: Execute test
              run: python ./github/tests/encoding_test.py